import argparse
import random
import time

from pythonosc import udp_client


if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.add_argument("--ip", default="127.0.0.1",
      help="The ip of the OSC server")
  parser.add_argument("--port", type=int, default=9000,
      help="The port the OSC server is listening on")
  args = parser.parse_args()

  client = udp_client.SimpleUDPClient(args.ip, args.port)

  # TailBlendH
  
if __name__ == '__main__':
    while True:
        client.send_message("/avatar/parameters/TailBool", 1)
        client.send_message("/avatar/parameters/TailToggle", 1)
        client.send_message("/avatar/parameters/TailX", -0.9)
        client.send_message("/avatar/parameters/TailH", -0.9)
        client.send_message("/avatar/parameters/TailBlendH", -0.9)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.8)
        client.send_message("/avatar/parameters/TailH", -0.8)
        client.send_message("/avatar/parameters/TailBlendH", -0.8)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.7)
        client.send_message("/avatar/parameters/TailH", -0.7)
        client.send_message("/avatar/parameters/TailBlendH", -0.7)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.6)
        client.send_message("/avatar/parameters/TailH", -0.6)
        client.send_message("/avatar/parameters/TailBlendH", -0.6)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.5)
        client.send_message("/avatar/parameters/TailH", -0.5)
        client.send_message("/avatar/parameters/TailBlendH", -0.5)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.4)
        client.send_message("/avatar/parameters/TailH", -0.4)
        client.send_message("/avatar/parameters/TailBlendH", -0.4)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.3)
        client.send_message("/avatar/parameters/TailH", -0.3)
        client.send_message("/avatar/parameters/TailBlendH", -0.3)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.2)
        client.send_message("/avatar/parameters/TailH", -0.2)
        client.send_message("/avatar/parameters/TailBlendH", -0.2)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.1)
        client.send_message("/avatar/parameters/TailH", -0.1)
        client.send_message("/avatar/parameters/TailBlendH", -0.1)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.0)
        client.send_message("/avatar/parameters/TailH", 0.0)
        client.send_message("/avatar/parameters/TailBlendH", 0.0)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.1)
        client.send_message("/avatar/parameters/TailH", 0.1)
        client.send_message("/avatar/parameters/TailBlendH", 0.1)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.2)
        client.send_message("/avatar/parameters/TailH", 0.2)
        client.send_message("/avatar/parameters/TailBlendH", 0.2)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.3)
        client.send_message("/avatar/parameters/TailH", 0.3)
        client.send_message("/avatar/parameters/TailBlendH", 0.3)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.4)
        client.send_message("/avatar/parameters/TailH", 0.4)
        client.send_message("/avatar/parameters/TailBlendH", 0.4)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.5)
        client.send_message("/avatar/parameters/TailH", 0.5)
        client.send_message("/avatar/parameters/TailBlendH", 0.5)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.6)
        client.send_message("/avatar/parameters/TailH", 0.6)
        client.send_message("/avatar/parameters/TailBlendH", 0.6)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.7)
        client.send_message("/avatar/parameters/TailH", 0.7)
        client.send_message("/avatar/parameters/TailBlendH", 0.7)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.8)
        client.send_message("/avatar/parameters/TailH", 0.8)
        client.send_message("/avatar/parameters/TailBlendH", 0.8)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.9)
        client.send_message("/avatar/parameters/TailH", 0.9)
        client.send_message("/avatar/parameters/TailBlendH", 0.9)
        time.sleep(0.05)
        client.send_message("/avatar/parameters/TailX", 1.0)
        client.send_message("/avatar/parameters/TailH", 1.0)
        client.send_message("/avatar/parameters/TailBlendH", 1.0)
        time.sleep(0.05)
        client.send_message("/avatar/parameters/TailX", 0.9)
        client.send_message("/avatar/parameters/TailH", 0.9)
        client.send_message("/avatar/parameters/TailBlendH", 0.9)
        time.sleep(0.05)
        client.send_message("/avatar/parameters/TailX", 0.8)
        client.send_message("/avatar/parameters/TailH", 0.8)
        client.send_message("/avatar/parameters/TailBlendH", 0.8)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.7)
        client.send_message("/avatar/parameters/TailH", 0.7)
        client.send_message("/avatar/parameters/TailBlendH", 0.7)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.6)
        client.send_message("/avatar/parameters/TailH", 0.6)
        client.send_message("/avatar/parameters/TailBlendH", 0.6)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.5)
        client.send_message("/avatar/parameters/TailH", 0.5)
        client.send_message("/avatar/parameters/TailBlendH", 0.5)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.4)
        client.send_message("/avatar/parameters/TailH", 0.4)
        client.send_message("/avatar/parameters/TailBlendH", 0.4)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.3)
        client.send_message("/avatar/parameters/TailH", 0.3)
        client.send_message("/avatar/parameters/TailBlendH", 0.3)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.2)
        client.send_message("/avatar/parameters/TailH", 0.2)
        client.send_message("/avatar/parameters/TailBlendH", 0.2)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.1)
        client.send_message("/avatar/parameters/TailH", 0.1)
        client.send_message("/avatar/parameters/TailBlendH", 0.1)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", 0.0)
        client.send_message("/avatar/parameters/TailH", 0.0)
        client.send_message("/avatar/parameters/TailBlendH", 0.0)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.1)
        client.send_message("/avatar/parameters/TailH", -0.1)
        client.send_message("/avatar/parameters/TailBlendH", -0.1)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.2)
        client.send_message("/avatar/parameters/TailH", -0.2)
        client.send_message("/avatar/parameters/TailBlendH", -0.2)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.3)
        client.send_message("/avatar/parameters/TailH", -0.3)
        client.send_message("/avatar/parameters/TailBlendH", -0.3)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.4)
        client.send_message("/avatar/parameters/TailH", -0.4)
        client.send_message("/avatar/parameters/TailBlendH", -0.4)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.5)
        client.send_message("/avatar/parameters/TailH", -0.5)
        client.send_message("/avatar/parameters/TailBlendH", -0.5)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.6)
        client.send_message("/avatar/parameters/TailH", -0.6)
        client.send_message("/avatar/parameters/TailBlendH", -0.6)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.7)
        client.send_message("/avatar/parameters/TailH", -0.7)
        client.send_message("/avatar/parameters/TailBlendH", -0.7)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.8)
        client.send_message("/avatar/parameters/TailH", -0.8)
        client.send_message("/avatar/parameters/TailBlendH", -0.8)
        time.sleep(0.1)
        client.send_message("/avatar/parameters/TailX", -0.9)
        client.send_message("/avatar/parameters/TailH", -0.9)
        client.send_message("/avatar/parameters/TailBlendH", -0.9)
        time.sleep(0.05)
        client.send_message("/avatar/parameters/TailX", -1.0)
        client.send_message("/avatar/parameters/TailH", -1.0)
        client.send_message("/avatar/parameters/TailBlendH", -1.0)
        time.sleep(0.05)
